baseURL = "/"
languageCode = "en-us"
title = "The Samizdat System"
theme = "kube"
description = "Your content, available"
Paginate = 4

[Params]
  RSSLink = "/index.xml"
  author = "The Samizdat System" # add your company name
  github = "tokahuke" # add your github profile name
  twitter = "" # add your twitter profile
  email = "pedrobittencourt3@gmail.com"

[[menu.main]]
    name = "Install"
    weight = 100
    url = "~/install/"
[[menu.main]]
    name = "Docs"
    weight = 200
    url = "~/docs/"
[[menu.main]]
    name = "Blog"
    weight = 300
    url = "~/blog/"
[[menu.main]]
    name = "Faq"
    weight = 400
    url = "~/faq/"
